services:
  mysql:
    container_name: mysql
    image: mysql:9.2.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: /rootPwd
      MYSQL_DATABASE: bookdb
      MYSQL_USER: bookusr
      MYSQL_PASSWORD: /BookAdm4546
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

volumes:
  mysql-data: